// The .json file will be generated by scripts
import tyrasStructureJson from "./tyras-structure.json";

export const tyrasStructure: TyrasStructure = Object.freeze(tyrasStructureJson);

// Need to wait for this before doing advanced type tricks on json files:
// https://stackoverflow.com/questions/69314862/typescript-json-module-deep-type-information
export type TyrasStructure = Readonly<
  Record<TyrasAspects, ReadonlyArray<string>>
>;

export type TyrasAspects = "dataValidation" | "server" | "client";

/**
 * Only applicable for server or client, not data validation
 */
export const ASPECT_NONE = "none";
