/**
 * @file This file defines type for tyras-versions.json file in this folder, which is generated by code in scripts folder. It is used by code both in src and scripts folders.
 */

export type TyrasVersions = Record<
  string,
  Record<VersionKind, Record<string, Versions>>
>;

export type VersionKind = "server" | "client";

export type Versions = ReadonlyArray<string>;
