// The .json file will be generated by scripts
import tyrasStructureJson from "./tyras-structure.json";
import type * as types from "./tyras-structure.types";

// Need to wait for this before doing advanced type tricks on json files:
// https://stackoverflow.com/questions/69314862/typescript-json-module-deep-type-information

export const tyrasStructure: types.TyrasStructure =
  Object.freeze(tyrasStructureJson);

/**
 * Only applicable for server or client, not data validation
 */
export const ASPECT_NONE = "none";
