// The .json file will be generated by scripts
import tyrasVersionsJson from "./tyras-versions.json";
import type * as types from "./tyras-versions.types";

export const tyrasVersions: types.TyrasVersions =
  Object.freeze(tyrasVersionsJson);

export const getVersions = (
  dataValidation: string,
  kind: types.VersionKind,
  component: string,
): types.Versions | undefined => tyrasVersions[dataValidation][kind][component];

export const getLatestVersion = (...args: Parameters<typeof getVersions>) =>
  getVersions(...args)?.[0];
