// The .json file will be generated by scripts
import tyrasVersionsJson from "./tyras-versions.json";

export const tyrasVersions: TyrasVersions = Object.freeze(tyrasVersionsJson);

export type TyrasVersions = Record<
  string,
  Record<VersionKind, Record<string, Versions>>
>;

export type VersionKind = "server" | "client";

export type Versions = ReadonlyArray<string>;

export const getVersions = (
  dataValidation: string,
  kind: VersionKind,
  component: string,
): Versions | undefined => tyrasVersions[dataValidation][kind][component];

export const getLatestVersion = (...args: Parameters<typeof getVersions>) =>
  getVersions(...args)?.[0];
