/**
 * @file This file defines type for tyras-versions.json file in this folder, which is generated by code in scripts folder. It is used by code both in src and scripts folders.
 */

import type * as consts from "./consts";

export interface TyrasVersions<TVersions = Versions> {
  specific: TyrasVersionsSpecific<TVersions>;
  protocol: Record<string, TVersions>;
}

export type TyrasVersionsSpecific<TVersions = Versions> = Record<
  string,
  Record<VersionKind, Record<string, TVersions>>
>;

export type VersionKind = VersionKindServer | VersionKindClient;

export type VersionKindServer = typeof consts.VERSION_KIND_SERVER;
export type VersionKindClient = typeof consts.VERSION_KIND_CLIENT;

export type Versions = ReadonlyArray<string>;
