/**
 * @file This file defines type for tyras-structure.json file in this folder, which is generated by code in scripts folder. It is used by code both in src and scripts folders.
 */

export type TyrasStructure<TKinds = ReadonlyArray<string>> = Record<
  TyrasAspects,
  TKinds
>;

export type TyrasAspects = "dataValidation" | "server" | "client";
